const data =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
                type:"div",
                screen:"shop",
                name:"test",
            }
        ]
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
]
