const data =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
                } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
          
          subscreen:[
            {
                name:"test-1",
                style:{
                    position:"absolute"
                },
            }
          ] ,     type:"div",
                screen:"shop",
                name:"test",
            }
        ],
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            subscreen:[
                {
                    name:"test-1",
                    style:{
                        position:"absolute"
                    },
                }
            ],
            top:0,
            backgroundColor:"red"
        }
    },
]

const dataV2 =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
                } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
          
          subscreen:[
            {
                name:"test-1",
                style:{
                    position:"absolute"
                },
            }
          ] ,     type:"div",
                screen:"shop",
                name:"test",
            }
        ],
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            subscreen:[
                {
                    name:"test-1",
                    style:{
                        position:"absolute"
                    },
                }
            ],
            top:0,
            backgroundColor:"red"
        }
    },
]

const dataV3 =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
                } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
          
          subscreen:[
            {
                name:"test-1",
                style:{
                    position:"absolute"
                },
            }
          ] ,     type:"div",
                screen:"shop",
                name:"test",
            }
        ],
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            subscreen:[
                {
                    name:"test-1",
                    style:{
                        position:"absolute"
                    },
                }
            ],
            top:0,
            backgroundColor:"red"
        }
    },
]

const dataV4 =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
                } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
          
          subscreen:[
            {
                name:"test-1",
                style:{
                    position:"absolute"
                },
            }
          ] ,     type:"div",
                screen:"shop",
                name:"test",
            }
        ],
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            subscreen:[
                {
                    name:"test-1",
                    style:{
                        position:"absolute"
                    },
                }
            ],
            top:0,
            backgroundColor:"red"
        }
    },
]

const dataV5 =[
    {
        id:1,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
                } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        },
        children:[
            {
                id:1,
          
          subscreen:[
            {
                name:"test-1",
                style:{
                    position:"absolute"
                },
            }
          ] ,     type:"div",
                screen:"shop",
                name:"test",
            }
        ],
    },
    {
        id:2,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],      
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:3,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:4,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:5,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:6,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            top:0,
            backgroundColor:"red"
        }
    },
    {
        id:7,
        type:"div",
        screen:"shop",
        name:"test",
        isActive:true,
        subscreen:[
            {
                status: "active",
                name:"test sub",
                subscreen:[
                    {
                        name:"test-1",
                        style:{
                            position:"absolute"
                        },
                    }
                ],
                style:{
                display:"block"
            } 
            }
        ],
        style:{ 
            with:2,
            height:2,
            position:"absolute",
            subscreen:[
                {
                    name:"test-1",
                    style:{
                        position:"absolute"
                    },
                }
            ],
            top:0,
            backgroundColor:"red"
        }
    },
]

